repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.4.0
        hooks:
        -   id: fix-encoding-pragma
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: check-yaml
        -   id: check-added-large-files
    -   repo: https://github.com/timothycrosley/isort
        rev: 5.6.4
        hooks:
        -   id: isort
    -   repo: https://github.com/psf/black
        rev: 20.8b1
        hooks:
        -   id: black
    -   repo: https://gitlab.com/pycqa/flake8.git
        rev: 3.8.4
        hooks:
        -   id: flake8
            args: [--max-line-length, "88"]
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: 'master'
        hooks:
        -   id: mypy
